"""add description to product snapshots

Revision ID: 6cdd45e7acec
Revises: 18240e50aabe
Create Date: 2026-08-01 23:49:53.522714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cdd45e7acec'
down_revision: Union[str, Sequence[str], None] = '18240e50aabe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_product_id'), 'recommendations', ['product_id'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('product_snapshots', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('product_snapshots', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('product_snapshots', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('ix_product_snapshots_id'), table_name='product_snapshots')
    op.drop_constraint(op.f('product_snapshots_product_id_key'), 'product_snapshots', type_='unique')
    op.drop_column('product_snapshots', 'id')
    op.alter_column('user_events', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_user_events_id'), table_name='user_events')
    op.create_index(op.f('ix_user_events_product_id'), 'user_events', ['product_id'], unique=False)
    op.create_index(op.f('ix_user_events_user_id'), 'user_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_events_user_id'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_product_id'), table_name='user_events')
    op.create_index(op.f('ix_user_events_id'), 'user_events', ['id'], unique=False)
    op.alter_column('user_events', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('product_snapshots', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint(op.f('product_snapshots_product_id_key'), 'product_snapshots', ['product_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_product_snapshots_id'), 'product_snapshots', ['id'], unique=False)
    op.alter_column('product_snapshots', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('product_snapshots', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('product_snapshots', 'description')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_product_id'), table_name='recommendations')
    op.drop_table('recommendations')
    # ### end Alembic commands ###
