"""add product fields

Revision ID: f902530d5c79
Revises: 3921ac3f9414
Create Date: 2026-07-31 23:03:09.661264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f902530d5c79'
down_revision: Union[str, Sequence[str], None] = '3921ac3f9414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_events_id'), table_name='user_events')
    op.drop_table('user_events')
    op.drop_index(op.f('ix_product_snapshots_id'), table_name='product_snapshots')
    op.drop_table('product_snapshots')
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_items', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'])
    op.add_column('orders', sa.Column('status', sa.Enum('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False))
    op.add_column('orders', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('orders', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('products', sa.Column('category', sa.String(), nullable=True))
    op.add_column('products', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('products', sa.Column('sku', sa.String(), nullable=True))
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'stock')
    op.drop_column('products', 'sku')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'category')
    op.alter_column('orders', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'status')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.alter_column('order_items', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('product_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('product_snapshots_pkey')),
    sa.UniqueConstraint('product_id', name=op.f('product_snapshots_product_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_product_snapshots_id'), 'product_snapshots', ['id'], unique=False)
    op.create_table('user_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_events_pkey'))
    )
    op.create_index(op.f('ix_user_events_id'), 'user_events', ['id'], unique=False)
    # ### end Alembic commands ###
